[package]
name = "kasane-logic"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "This is Kasane-logic"

[dependencies]
roaring = "0.11.3"
rand = "0.9.2"
rayon = "1.8"

[dev-dependencies]