[package]
name = "kasane-logic"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "This is Kasane-logic"

[dependencies]
roaring = "0.11.3"
rand = { version = "0.9.2", optional = true }

[features]
random = [ "rand" ]

[dev-dependencies]
cargo-husky = "1.5.0"
rand = "0.9.2"
proptest = "1.10.0"
rand_chacha = "0.10.0"
criterion = "0.8.2"

[[bench]]
name = "set"
harness = false
required-features = ["random"]

