[package]
name = "kasane-logic"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "This is Kasane-logic"

[dependencies]
roaring = "0.11.3"
rand = { version = "0.9.2", optional = true }
futures = "0.3"

# Wasm以外の環境でのみ tokio を有効化
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }

[features]
random = [ "rand" ]

[dev-dependencies]
cargo-husky = "1"
rand = "0.9.2"
proptest = "1.9.0"
rand_chacha = "0.9.0"
criterion = "0.8.1"

[[bench]]
name = "set"
harness = false
required-features = ["random"]

