[package]
name = "kasane-logic"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "This is Kasane-logic"

[dependencies]
roaring = "0.11.3"
rand = { version = "0.9.2", optional = true }
rayon = "1.8"

[features]
random = [ "rand" ]